### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement sipfullproxy (from versions: none)

### ISSUE THREAD

**Issue by RogueThread** [jasonxtn/Kraken#3]
`pip install -r requirements.txt`

ERROR: Could not find a version that satisfies the requirement sipfullproxy (from versions: none)
ERROR: No matching distribution found for sipfullproxy

**Comment by jasonxtn** [comment]
Problem Fixed ! 
Just re-clone the repositorie and re-install requirements.txt : 
```
git clone https://github.com/jasonxtn/kraken.git
cd Kraken
pip install -r requirements.txt
```
