### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/<path>/Logs/admin_panel_finder.log'

### ISSUE THREAD

**Issue by RogueThread** [jasonxtn/Kraken#4]
```
./kraken.py
> 30
```

Traceback (most recent call last):
  File "/<path>/files/admin_panel_finder.py", line 16, in <module>
    logging.basicConfig(filename=os.path.join('Logs', 'admin_panel_finder.log'),
  File "/usr/lib/python3.12/logging/__init__.py", line 2118, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/<path>/Logs/admin_panel_finder.log'

**Comment by jasonxtn** [comment]
Sorry my mistake i forgot to add a function to create the file in case not exist anyway problem solved.
You can just Just re-clone the repositorie  :
`git clone https://github.com/jasonxtn/kraken.git`
or head to 'Logs' directory and create a file : admin_panel_finder.log
