### ISSUE TITLE
pyfiglet module not found 

### ISSUE THREAD

**Issue by AmanBhatnagar12** [jasonxtn/Kraken#6]
Hey there ,
I tried running **Kraken** tool on my **Kali Linux workstation** ,what happens is that because of module **pyfiglet** the tool aborts its process and doesn't continue to run .

So either update the readme  making them install this module or make changes in code so that this tool works perfectly for pen testing purposes ,

**Comment by jasonxtn** [comment]
Hi sir,
Sorry for late answer,
just type in terminal : pip install pyfiglet or cd to the Kraken Directory then type pip install -r requirements.txt
